
[monitors]

    [monitors.any]
    # padding  = [left, top, bottom, right]
    padding = [40,40,40,40]
    # default_size = [width, height]
    default_size = [900,700]
    # margin  = [margin_x, margin_y]
    margin = [8,8]
    
    detect_padding = true
    classic_resize = false
    stick_to_borders = true
    invert_keys_in_stick_mode = true
    resize_through_borders = false


    # [monitors.0]
    # padding = [30,30,30,30]
    # default_size = [700,600]
    # margin = [2,2]

    # detect_padding = true 
    # classic_resize = false 
    # stick_to_borders = true 
    # invert_keys_in_stick_mode = true
    # resize_through_borders = false 


[windows]

    ## [windows.window_class]

    #[windows.kitty]
    #minimal_size = [80,80]

    ## monitor_n = [window_size_x, window_size_y]
    #monitor_any = [500,500]
    #monitor_0 = [600, 500]
    #monitor_1 = [700, 600]


    [windows.firefox]
    minimal_size = [450,120]
           
    [windows."io.bassi.Amberol"]
    minimal_size = [360,660]

