
[monitors]

    [monitors.main]
    # margins = [left, top, bottom, right]
    padding = [20,20,20,20]
    #size = [width, height]
    size = [900,700]

    detect_borders = true
    classic_resize = false
    stick_to_borders  = true
    invert_keys_in_stick_mode = true
    resize_through_borders = false


    # [monitors.0]
    # margins = [30,30,30,30]
    # size = [700,600]

    # detect_borders = true
    # classic_resize = false
    # stick_to_borders  = true
    # invert_keys_in_stick_mode = true
    # resize_through_borders = false


[windows]

    # [windows.kitty]
    # monitor_0 = [600, 500]
    # monitor_1 = [700, 600]
