[package]
name = "hyprfloat"
version = "0.1.0"
edition = "2021"

[lib]
name = "hyprfloat"
path = "src/lib.rs"

[[bin]]
name = "hfuni"
path = "src/bin/hfuni.rs"


#[toolchain]
#toolchain = "nightly"

[dependencies]
signal-hook = "0.3"
clap_complete = "4.5"
clap = { version = "4.5.29", features = ["derive"] }
#clap = {git = "https://github.com/clap-rs/clap", branch ="master"}
hyprland = { git = "https://github.com/jvc84/hyprland-rs", branch = "master" }
#hyprland = { path = "/home/adex/applications/hyprland-rs", branch = "master" }
toml = "0.8"
serde = "1.0"
rand = "0.9"
lazy_static = "1.5"
simple-home-dir = "0.4"
serde_json = "1.0"
tokio = { version = "1.43", features = ["full"] }


[profile.release]
opt-level = 3
lto = true
codegen-units = 16
panic = "abort"
debug = 0
