[package]
name = "hyprfloat"
version = "0.1.0"
edition = "2021"

[lib]
name = "hyprfloat"
path = "src/lib.rs"


[[bin]]
name = "move"
path = "src/bin/move.rs"

[[bin]]
name = "open"
path = "src/bin/open.rs"

[[bin]]
name = "resize"
path = "src/bin/resize.rs"

[[bin]]
name = "rtest"
path = "src/bin/rtest.rs"

[dependencies]
dict = "0.1.5"
fork = "0.2.0"
#hyprland = "0.3.13" # doesn't need

#hyprland = { git = "https://github.com/hyprland-community/hyprland-rs", branch = "master" }
hyprland = "0.4.0-alpha.2"
toml = "0.8.19"
#serde = {version =  "1.0.201", features = ["derive"] }
serde = "1.0.204"
directories = "5.0.1"
rand = "0.9.0-alpha.2"
log = "0.4.22"

[profile.release]
target_os = "linux"
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"


#[profile.release]
#target_os = "linux"
#opt-level = "s"
#lto = false
#codegen-units = 16instruction
#panic = "abort"
